/*
� [2026] Microchip Technology Inc. and its subsidiaries.

    Subject to your compliance with these terms, you may use Microchip 
    software and any derivatives exclusively with Microchip products. 
    You are responsible for complying with 3rd party license terms  
    applicable to your use of 3rd party software (including open source  
    software) that may accompany Microchip software. SOFTWARE IS ?AS IS.? 
    NO WARRANTIES, WHETHER EXPRESS, IMPLIED OR STATUTORY, APPLY TO THIS 
    SOFTWARE, INCLUDING ANY IMPLIED WARRANTIES OF NON-INFRINGEMENT,  
    MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE. IN NO EVENT 
    WILL MICROCHIP BE LIABLE FOR ANY INDIRECT, SPECIAL, PUNITIVE, 
    INCIDENTAL OR CONSEQUENTIAL LOSS, DAMAGE, COST OR EXPENSE OF ANY 
    KIND WHATSOEVER RELATED TO THE SOFTWARE, HOWEVER CAUSED, EVEN IF 
    MICROCHIP HAS BEEN ADVISED OF THE POSSIBILITY OR THE DAMAGES ARE 
    FORESEEABLE. TO THE FULLEST EXTENT ALLOWED BY LAW, MICROCHIP?S 
    TOTAL LIABILITY ON ALL CLAIMS RELATED TO THE SOFTWARE WILL NOT 
    EXCEED AMOUNT OF FEES, IF ANY, YOU PAID DIRECTLY TO MICROCHIP FOR 
    THIS SOFTWARE.
*/
#include <stdio.h>
#include "mcc_generated_files/system/system.h"
#include "mcc_generated_files/system/clock.h"
#include "mcc_generated_files/system/reset.h"
#include "mcc_generated_files/system/traps.h"
#include "mcc_generated_files/system/interrupt.h"
#include "mcc_generated_files/timer/tmr1.h"
#include "mcc_generated_files/system/pins.h"
#include "mcc_generated_files/spi_host/spi2.h"
#include "mcc_generated_files/uart/uart1.h"
#include "network.h"
#include "ENC28J60.h"
#include "../../ENC28_SPI_Ethernet/TCP_APP/tcp_server_demo.h"
#include "../../ENC28_SPI_Ethernet/TCP_APP/web_status_demo.h"
#include "../../ENC28_SPI_Ethernet/TCPIPLibrary/log_console.h"
#include "../../ENC28_SPI_Ethernet/TCPIPLibrary/rtcc.h"
#include "../TCPIPLibrary/tcpv4.h"
#include "../TCPIPLibrary/ipv4.h"
#include "../TCPIPLibrary/tcpip_config.h"

/*
    Main application
*/
#define RETRNMIT_RXTO_PRINTF

// create the socket for the TCP Server
 static tcpTCB_t port7TCB;

 // create the TX and RX Server's buffers
 static uint8_t rxdataPort7[20];
 static uint8_t txdataPort7[20];

 uint16_t rxLen, txLen, i;
 socketState_t socket_state;


volatile uint16_t dly_100 = 0;
// Ethernet chip select is wired to the CS2 (RD3) pin generated by MCC
static void ETH_CS_Low(void)  { CS2_SetLow(); }
static void ETH_CS_High(void) { CS2_SetHigh(); }

// Busy-wait delay used by the ENC28 driver; not cycle-accurate but sufficient for its timeouts
static void ETH_DelayUs(unsigned long long us)
{
    uint32_t cycles = (uint32_t)(us * (CLOCK_InstructionFrequencyGet() / 1000000UL));
    while (cycles--) { Nop(); }
}

// Last-resort recovery hook used by the ENC28 driver on unrecoverable DMA timeouts
static void ETH_SoftReset(void)
{
    asm volatile ("reset");
}

static void UART_WriteString(const char *s)
{
    while (*s) { UART1_Write((uint8_t)*s++); }
}

// raw polled write straight to the UART1 hardware, bypassing the interrupt-driven
// TX queue entirely - used from the trap handler below, since that queue can only
// drain via a TX interrupt that will never fire while we're stuck in a trap ISR
static void UART_RawWriteString(const char *s)
{
    while (*s)
    {
        while (U1STAHbits.UTXBF) { }
        U1TXREG = (uint8_t)*s++;
    }
}

// strong override of traps.c's weak stub - guarantees the trap is visible even
// if the resulting halt/reset never lets execution return to printResetCause()
void TRAPS_halt_on_error(uint16_t code)
{
    char buf[48];
    // block any further/nested interrupt re-entry so the print below can never
    // be interleaved/garbled by a storm of the same condition re-triggering
    __builtin_disable_interrupts();
    sprintf(buf, "\r\n*** TRAP code=%u ***\r\n", (unsigned)code);
    UART_RawWriteString(buf);
#ifdef __DEBUG
    __builtin_software_breakpoint();
    while(1) { }
#else
    __asm__ volatile ("reset");
#endif
}

// catch-all for any interrupt with no assigned handler (e.g. a misconfigured or
// floating interrupt line) - traps.c only defines the named traps below this,
// so without this override a spurious vector silently freezes the CPU at an
// interrupt priority high enough to block even TMR1's heartbeat, with no trace
void __attribute__((interrupt, no_auto_psv)) _DefaultInterrupt(void)
{
    char buf[64];
    uint16_t vec;
    // block any further/nested interrupt re-entry so the print below can never
    // be interleaved/garbled by a storm of the same condition re-triggering
    __builtin_disable_interrupts();
    vec = INTERRUPT_VectorNumberGet();
    sprintf(buf, "\r\n*** SPURIOUS INTERRUPT vector=%u ***\r\n", (unsigned)vec);
    UART_RawWriteString(buf);
#ifdef __DEBUG
    __builtin_software_breakpoint();
    while(1) { }
#else
    __asm__ volatile ("reset");
#endif
}

// prints why we booted (trap/WDT/external/software/normal power-up) - a silent
// trap-triggered "reset" instruction (see traps.c) would otherwise look
// identical to a hang, since it produces no UART output of its own
static void printResetCause(void)
{
    uint16_t rcon = RESET_CauseGet();
    char buf[100];
    sprintf(buf, "\r\nRESET CAUSE: RCON=0x%04X%s%s%s%s%s\r\n", rcon,
        (rcon & RESET_MASK_TRAPR)  ? " TRAP" : "",
        (rcon & RESET_MASK_IOPUWR) ? " ILLOP" : "",
        (rcon & RESET_MASK_CM)     ? " CFGMISMATCH" : "",
        (rcon & RESET_MASK_SWR)    ? " SOFTWARE" : "",
        (rcon & RESET_MASK_WDTO)   ? " WATCHDOG" : "");
    UART_WriteString(buf);
    RESET_CauseClearAll();
}



void ms100(void){
    LED0_Toggle();
    dly_100++;

    // rtcc_handler() must fire once per second to drive time() forward;
    // without it, Network_Manage()'s TCP timeout/retransmission and ARP
    // aging never run at all since they're gated on time() changing
    static uint8_t rtccTickCount = 0;
    rtccTickCount++;
    if (rtccTickCount >= 10)
    {
        rtccTickCount = 0;
        rtcc_handler();
    }
}

// Placeholder hooks required by web_status_demo.c until a real ADC/pin manager is wired up
uint16_t App_GetAnalog(uint8_t channel)
{
    (void)channel;
    return 0;
}

uint8_t App_GetDigital(uint8_t pin)
{
    (void)pin;
    return 0;
}

// Blink LED1 'count' times (~200ms each), then pause ~1s, forever. Never returns.
static void blinkFault(uint8_t count)
{
    while(1)
    {
        uint8_t i;
        for (i = 0; i < count; i++)
        {
            LED1_SetHigh();
            dly_100 = 0; while(dly_100 < 1);
            LED1_SetLow();
            dly_100 = 0; while(dly_100 < 1);
        }
        dly_100 = 0; while(dly_100 < 10);
    }
}

int main(void)
{
     
    SYSTEM_Initialize();
    WDTCONLbits.ON = false;
    // Route the stack's console logging through the UART driver's queued,
    // interrupt-driven writer instead of blocking on raw hardware access
    LOG_ConsoleSetOutput(UART1_Write);
    printResetCause();

    TMR1_TimeoutCallbackRegister(&ms100);
    TMR1_Start();
  
    
   bool spiOk = SPI2_Open(HOST_CONFIG);
  

    static const enc28_hal_t enc28_hal = {
        .spi_exchange = SPI2_ByteExchange,
        .cs_low       = ETH_CS_Low,
        .cs_high      = ETH_CS_High,
        .delay_us     = ETH_DelayUs,
        .soft_reset   = ETH_SoftReset,
    };

    if (ENC28_InitHAL(&enc28_hal) != 0)
    {
        blinkFault(1); // HAL misconfigured (a required callback was NULL)
    }

    // Raw SPI sanity check: EREVID is never 0x00/0xFF on a responding ENC28J60.
    // Keep retrying (instead of a single one-shot read) so the SPI transaction
    // is repeated continuously and easy to catch/trigger on a scope.
    uint8_t revId;
    do
    {
        revId = ENC28_Test(J60_EREVID);
        if (revId == 0x00 || revId == 0xFF)
        {
            LED1_SetHigh();
            dly_100 = 0; while(dly_100 < 1);
            LED1_SetLow();
            dly_100 = 0; while(dly_100 < 1);
        }
    } while (revId == 0x00 || revId == 0xFF);

    int netStatus = Network_Init();
    
    dly_100 = 0;
    if (netStatus == 0)
    {
        while(dly_100 < 19){
            if(spiOk)
                LED1_SetHigh();
        }
        LED1_SetLow();
    }
    else
    {
        blinkFault(2 + (uint8_t)netStatus); // 3 = ETH init failed, 4 = link timeout
    }
/*
    while(1)
    {
        static uint32_t lastRxCount = 0;
        uint32_t rxCount = Network_GetRxPacketCount();

        // UART loopback test: echo back whatever byte comes in on UART1
        if (UART1_IsRxReady())
        {
            UART1_Write(UART1_Read());
        }

        Network_Manage();
      //  TCP_Demo_Web_Status();

        if (rxCount != lastRxCount)
        {
            LED1_Toggle(); // pulse LED1 on every received Ethernet frame (RX activity indicator)
            lastRxCount = rxCount;
        }
    }    
}
 */
   while(1){
    Network_Manage();
    socket_state = TCP_SocketPoll(&port7TCB);
    //printf("%d\r\n",socket_state);
    switch(socket_state)
    {
        case NOT_A_SOCKET:
            
        //Inserting and Initializing the socket
            TCP_SocketInit(&port7TCB);
            break;
        case SOCKET_CLOSED:
        // Configure the local port
            TCP_Bind(&port7TCB, 23000);
           
            // add receive buffer
            TCP_InsertRxBuffer(&port7TCB, rxdataPort7, sizeof(rxdataPort7));
            
            
        // Start the TCP server: Listen on port
            TCP_Listen(&port7TCB);
           
            break;
        case SOCKET_IN_PROGRESS:
            // handshake already under way - TCP_Listen() resets localSeqno
            // unconditionally, so don't call it again until the socket closes
            break;
        case SOCKET_CONNECTED:
            if (port7TCB.fsmState == CLOSE_WAIT)
            {
                // peer closed their side - close ours too, or this socket is
                // stuck forever and this demo can never accept another client
                TCP_Close(&port7TCB);
                break;
            }

            // check if the buffer was sent, if yes we can send another buffer
            if(TCP_SendDone(&port7TCB))
            {
                // check to see  if there are any received data
                rxLen = TCP_GetRxLength(&port7TCB);
                if(rxLen > 0)
                {
                    rxLen = TCP_GetReceivedData(&port7TCB);

                    //simulate some buffer processing
                    for(i = 0; i < rxLen; i++)
                    {
                        txdataPort7[i] = rxdataPort7[i];
                    }

                    // reuse the RX buffer
#ifdef RETRNMIT_RXTO_PRINTF
                    printf("%.*s\r\n", (int)rxLen, (char *)rxdataPort7);
#endif
                    TCP_InsertRxBuffer(&port7TCB, rxdataPort7, sizeof(rxdataPort7));
                    txLen = rxLen;
                    //send data back to the source
                    TCP_Send(&port7TCB, txdataPort7, txLen);
                }
            }
            break;
        case SOCKET_CLOSING:
            TCP_SocketRemove(&port7TCB);
            break;
            
        default:
            // we should not end up here
             blinkFault(5); // 3 = ETH init failed, 4 = link timeout
            break;
        }
    } 
}

