/*
� [2026] Microchip Technology Inc. and its subsidiaries.

    Subject to your compliance with these terms, you may use Microchip 
    software and any derivatives exclusively with Microchip products. 
    You are responsible for complying with 3rd party license terms  
    applicable to your use of 3rd party software (including open source  
    software) that may accompany Microchip software. SOFTWARE IS ?AS IS.? 
    NO WARRANTIES, WHETHER EXPRESS, IMPLIED OR STATUTORY, APPLY TO THIS 
    SOFTWARE, INCLUDING ANY IMPLIED WARRANTIES OF NON-INFRINGEMENT,  
    MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE. IN NO EVENT 
    WILL MICROCHIP BE LIABLE FOR ANY INDIRECT, SPECIAL, PUNITIVE, 
    INCIDENTAL OR CONSEQUENTIAL LOSS, DAMAGE, COST OR EXPENSE OF ANY 
    KIND WHATSOEVER RELATED TO THE SOFTWARE, HOWEVER CAUSED, EVEN IF 
    MICROCHIP HAS BEEN ADVISED OF THE POSSIBILITY OR THE DAMAGES ARE 
    FORESEEABLE. TO THE FULLEST EXTENT ALLOWED BY LAW, MICROCHIP?S 
    TOTAL LIABILITY ON ALL CLAIMS RELATED TO THE SOFTWARE WILL NOT 
    EXCEED AMOUNT OF FEES, IF ANY, YOU PAID DIRECTLY TO MICROCHIP FOR 
    THIS SOFTWARE.
*/
#include "mcc_generated_files/system/system.h"
#include "mcc_generated_files/system/clock.h"
#include "mcc_generated_files/timer/timer_interface.h"
#include "mcc_generated_files/system/pins.h"
#include "mcc_generated_files/spi_host/spi2.h"
#include "mcc_generated_files/uart/uart1.h"
#include "network.h"
#include "ENC28J60.h"
#include "../../ENC28_SPI_Ethernet/TCP_APP/tcp_server_demo.h"
#include "../../ENC28_SPI_Ethernet/TCP_APP/web_status_demo.h"
#include "../../ENC28_SPI_Ethernet/TCPIPLibrary/log_console.h"
#include "../../ENC28_SPI_Ethernet/TCPIPLibrary/rtcc.h"
/*
    Main application
*/
volatile uint16_t dly_100 = 0;
// Ethernet chip select is wired to the CS2 (RD3) pin generated by MCC
static void ETH_CS_Low(void)  { CS2_SetLow(); }
static void ETH_CS_High(void) { CS2_SetHigh(); }

// Busy-wait delay used by the ENC28 driver; not cycle-accurate but sufficient for its timeouts
static void ETH_DelayUs(unsigned long long us)
{
    uint32_t cycles = (uint32_t)(us * (CLOCK_InstructionFrequencyGet() / 1000000UL));
    while (cycles--) { Nop(); }
}

// Last-resort recovery hook used by the ENC28 driver on unrecoverable DMA timeouts
static void ETH_SoftReset(void)
{
    asm volatile ("reset");
}

void ms100(void){
    LED0_Toggle();
    dly_100++;

    // rtcc_handler() must fire once per second to drive time() forward;
    // without it, Network_Manage()'s TCP timeout/retransmission and ARP
    // aging never run at all since they're gated on time() changing
    static uint8_t rtccTickCount = 0;
    rtccTickCount++;
    if (rtccTickCount >= 10)
    {
        rtccTickCount = 0;
        rtcc_handler();
    }
}

// Placeholder hooks required by web_status_demo.c until a real ADC/pin manager is wired up
uint16_t App_GetAnalog(uint8_t channel)
{
    (void)channel;
    return 0;
}

uint8_t App_GetDigital(uint8_t pin)
{
    (void)pin;
    return 0;
}

// Blink LED1 'count' times (~200ms each), then pause ~1s, forever. Never returns.
static void blinkFault(uint8_t count)
{
    while(1)
    {
        uint8_t i;
        for (i = 0; i < count; i++)
        {
            LED1_SetHigh();
            dly_100 = 0; while(dly_100 < 1);
            LED1_SetLow();
            dly_100 = 0; while(dly_100 < 1);
        }
        dly_100 = 0; while(dly_100 < 10);
    }
}

int main(void)
{
    SYSTEM_Initialize();

    // Route the stack's console logging through the UART driver's queued,
    // interrupt-driven writer instead of blocking on raw hardware access
    LOG_ConsoleSetOutput(UART1_Write);

    TMR1_TimeoutCallbackRegister(&ms100);
    TMR1_Start();
  
    
   bool spiOk = SPI2_Open(HOST_CONFIG);
  

    static const enc28_hal_t enc28_hal = {
        .spi_exchange = SPI2_ByteExchange,
        .cs_low       = ETH_CS_Low,
        .cs_high      = ETH_CS_High,
        .delay_us     = ETH_DelayUs,
        .soft_reset   = ETH_SoftReset,
    };

    if (ENC28_InitHAL(&enc28_hal) != 0)
    {
        blinkFault(1); // HAL misconfigured (a required callback was NULL)
    }

    // Raw SPI sanity check: EREVID is never 0x00/0xFF on a responding ENC28J60.
    // Keep retrying (instead of a single one-shot read) so the SPI transaction
    // is repeated continuously and easy to catch/trigger on a scope.
    uint8_t revId;
    do
    {
        revId = ENC28_Test(J60_EREVID);
        if (revId == 0x00 || revId == 0xFF)
        {
            LED1_SetHigh();
            dly_100 = 0; while(dly_100 < 1);
            LED1_SetLow();
            dly_100 = 0; while(dly_100 < 1);
        }
    } while (revId == 0x00 || revId == 0xFF);

    int netStatus = Network_Init();
    
    dly_100 = 0;
    if (netStatus == 0)
    {
        while(dly_100 < 19){
            if(spiOk)
                LED1_SetHigh();
        }
        LED1_SetLow();
    }
    else
    {
        blinkFault(2 + (uint8_t)netStatus); // 3 = ETH init failed, 4 = link timeout
    }

    while(1)
    {
        static uint32_t lastRxCount = 0;
        uint32_t rxCount = Network_GetRxPacketCount();

        // UART loopback test: echo back whatever byte comes in on UART1
        if (UART1_IsRxReady())
        {
            UART1_Write(UART1_Read());
        }

        Network_Manage();
        TCP_Demo_Web_Status();

        if (rxCount != lastRxCount)
        {
            LED1_Toggle(); // pulse LED1 on every received Ethernet frame (RX activity indicator)
            lastRxCount = rxCount;
        }
    }    
}